### ISSUE TITLE
a negative number of confirmations?

### ISSUE THREAD

**Issue by Th0rgal** [ofek/bit#127]
Hello,

I am currently testing my app built with bit. I'm using the bitcoin testnet and I noticed the function .get_balance took in  account unconfirmed transactions. 
I would like the transactions to have at least one confirmation (and if possible a configurable number) to be counted in the balance. I then tried to create my own function:
```python
    def fetch_balance(self):
        balance = 0
        for unspent in self.key.get_unspents():
            print(unspent)
            if unspent.confirmations >= BitcoinTicket.validations:
                balance += unspent.amount
        return balance
```
Here is what I got from the print:
```python
Unspent(amount=50000, confirmations=-1805169, script='a914b98e3212e5afe4363942ce9b7b21c7057241782f87', txid='d594eb22bafcb8363271734e6d2e71d35e72cffc635e64f4f7b840ca605f6283', txindex=0, segwit=True)
Unspent(amount=1, confirmations=-1804929, script='a914b98e3212e5afe4363942ce9b7b21c7057241782f87', txid='194e7b59a8ea2fa1ce21664a81784dc7f7cf0cde0892df2356ff6da34b14f314', txindex=0, segwit=True)
```
According to this website: https://blockstream.info/testnet/address/2NAAMLhL3gGsPb67LwZ3bgPkbX93j8e3Vn9
I should have get 6 and 246 confirmations.
What does that mean? Is this only for testnet?

**Comment by Th0rgal** [comment]
I updated to 0.7.0, unfortunately this didn't fix the bug. To get the right confirmations number I can add 1805352. 
e.g. -1805169+1805352=6

**Comment by teran-mckinney** [comment]
This definitely sounds like an issue with our code interacting with one of the APIs. I don't have time to look into it right now, though.

**Comment by bjarnemagnussen** [comment]
Are you using testnet in this case? I just saw that the fix released with 0.7.0 is only for mainnet and not testnet. 

@pedr0-fr or @ofek is that something you can look into regarding a fix for testnet? Commit defa2e6b9afe9f45e5d0928489dcfc888a706d81 fixed the issue inside `get_unspent` but should also add the fix inside `get_unspent_testnet` method.

**Comment by pedr0-fr** [comment]
@bjarnemagnussen The PR I submitted (#129) just now should fix it. Also noticed that the confirmations from the BlockstreamAPI were off by one.

@Th0rgal , as @bjarnemagnussen said, that's a bug that won't occur on mainnet due to #120 . For now, just assume that a negative number of confirmations means zero confirmations.

**Comment by Th0rgal** [comment]
Alright thanks for your help! Yes I was using testnet. Should I close the issue ?

**Comment by pedr0-fr** [comment]
I think you can leave it open as it will be closed when #129 is merged

**Comment by GauthamramRavichandran** [comment]
The negative confirmations still appear in 0.7.1 in **testnet** while getting from **blockchair**,

Before getting any confirmations,
`[Unspent(amount=100000, confirmations=0, script='76a914c74cb99a461563e23843122607452724fbea5d2e88ac', txid='e49ea4a58d5cd121f1c3e9fdd41e8db674d07587837613f25f67d9b44eb7ae0e', txindex=0, segwit=False, sequence=4294967295)]`

After getting a confirmation, **negative values occur**,
`[Unspent(amount=100000, confirmations=-1807149, script='76a914c74cb99a461563e23843122607452724fbea5d2e88ac', txid='e49ea4a58d5cd121f1c3e9fdd41e8db674d07587837613f25f67d9b44eb7ae0e', txindex=0, segwit=False, sequence=4294967295)]`

**Comment by pedr0-fr** [comment]
I have checked this, this is an issue with BlockChairAPI, not with bit.

(will add details)
